// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Area: typeof import('./src/components/Editor/Area.vue')['default']
    ComponentList: typeof import('./src/components/componentList/src/componentList.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Preview: typeof import('./src/components/Editor/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/Toolbar/src/toolbar.vue')['default']
  }
}
